//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.LanguageResources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestProject.LanguageResources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not found.
        /// </summary>
        public static string AccountNotFound {
            get {
                return ResourceManager.GetString("AccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlertMessege.
        /// </summary>
        public static string AlertMessege {
            get {
                return ResourceManager.GetString("AlertMessege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes accepted.
        /// </summary>
        public static string ChangesAccepted {
            get {
                return ResourceManager.GetString("ChangesAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a source.
        /// </summary>
        public static string ChooseASource {
            get {
                return ResourceManager.GetString("ChooseASource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password:.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password must be compare Password.
        /// </summary>
        public static string ConfirmPasswordMustBeComparePassword {
            get {
                return ResourceManager.GetString("ConfirmPasswordMustBeComparePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmPassword must be required.
        /// </summary>
        public static string ConfirmPasswordMustBeRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordMustBeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want delete this task?.
        /// </summary>
        public static string DoYouWantDeleteThisTask {
            get {
                return ResourceManager.GetString("DoYouWantDeleteThisTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want logout?.
        /// </summary>
        public static string DoYouWantLogout {
            get {
                return ResourceManager.GetString("DoYouWantLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File doesn&apos;t exist. Maybe you moved or Exported it earlier. Re run the app..
        /// </summary>
        public static string FileDoesntExistMaybeYouMovedOrExportedItEarlieReRunTheApp {
            get {
                return ResourceManager.GetString("FileDoesntExistMaybeYouMovedOrExportedItEarlieReRunTheApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you go on TaskyDrop whithout save, you changes will be lose! Do you want this?.
        /// </summary>
        public static string IfYouGoOnTaskyDropWithoutSaveYourChangesWillBeLoseDoYouWantThis {
            get {
                return ResourceManager.GetString("IfYouGoOnTaskyDropWithoutSaveYourChangesWillBeLoseDoYouWantThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login already use!.
        /// </summary>
        public static string LoginAlreadyUse {
            get {
                return ResourceManager.GetString("LoginAlreadyUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login must be required.
        /// </summary>
        public static string LoginMustBeRequired {
            get {
                return ResourceManager.GetString("LoginMustBeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login use.
        /// </summary>
        public static string LoginUse {
            get {
                return ResourceManager.GetString("LoginUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My located.
        /// </summary>
        public static string MyLocated {
            get {
                return ResourceManager.GetString("MyLocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password:.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New task.
        /// </summary>
        public static string NewTask {
            get {
                return ResourceManager.GetString("NewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note must be required.
        /// </summary>
        public static string NoteMustBeRequired {
            get {
                return ResourceManager.GetString("NoteMustBeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password:.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password field must be required.
        /// </summary>
        public static string OldPasswordFieldMustBeRequired {
            get {
                return ResourceManager.GetString("OldPasswordFieldMustBeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be required.
        /// </summary>
        public static string PasswordMustBeRequired {
            get {
                return ResourceManager.GetString("PasswordMustBeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must content 8 char!.
        /// </summary>
        public static string PasswordMustContent8Char {
            get {
                return ResourceManager.GetString("PasswordMustContent8Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must content 8 char, number char and upper char..
        /// </summary>
        public static string PasswordMustContent8CharNumberCharAndUpperChar {
            get {
                return ResourceManager.GetString("PasswordMustContent8CharNumberCharAndUpperChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must content number char!.
        /// </summary>
        public static string PasswordMustContentNumber {
            get {
                return ResourceManager.GetString("PasswordMustContentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must content upper char!.
        /// </summary>
        public static string PasswordMustContentUpperChar {
            get {
                return ResourceManager.GetString("PasswordMustContentUpperChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Source.
        /// </summary>
        public static string PhotoSource {
            get {
                return ResourceManager.GetString("PhotoSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrate successful! Return on Login Page?.
        /// </summary>
        public static string RegistrateSuccessfulReturnOnLoginPage {
            get {
                return ResourceManager.GetString("RegistrateSuccessfulReturnOnLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Page.
        /// </summary>
        public static string RegistrationPage {
            get {
                return ResourceManager.GetString("RegistrationPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Error.
        /// </summary>
        public static string RegularError {
            get {
                return ResourceManager.GetString("RegularError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Picture.
        /// </summary>
        public static string SelectPicture {
            get {
                return ResourceManager.GetString("SelectPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks List.
        /// </summary>
        public static string TasksList {
            get {
                return ResourceManager.GetString("TasksList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fields Password and PasswordConfirmation should be equals.
        /// </summary>
        public static string TheFieldsPasswordAndPasswordConfirmationShouldBeEquals {
            get {
                return ResourceManager.GetString("TheFieldsPasswordAndPasswordConfirmationShouldBeEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title must be required.
        /// </summary>
        public static string TitleMustBeRequired {
            get {
                return ResourceManager.GetString("TitleMustBeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong data, account not found!.
        /// </summary>
        public static string WrongDataAccountNotFound {
            get {
                return ResourceManager.GetString("WrongDataAccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong old password!.
        /// </summary>
        public static string WrongOldPassword {
            get {
                return ResourceManager.GetString("WrongOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Password confirm!.
        /// </summary>
        public static string WrongPasswordConfirm {
            get {
                return ResourceManager.GetString("WrongPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t registrate when field is empty!.
        /// </summary>
        public static string YouCantRegistrateWhenFieldIsEmpty {
            get {
                return ResourceManager.GetString("YouCantRegistrateWhenFieldIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t save task when field is empty!.
        /// </summary>
        public static string YouCantSaveTaskWhenFieldIsEmpty {
            get {
                return ResourceManager.GetString("YouCantSaveTaskWhenFieldIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have camera.
        /// </summary>
        public static string YouDontHaveCamera {
            get {
                return ResourceManager.GetString("YouDontHaveCamera", resourceCulture);
            }
        }
    }
}
